---
# Test Camera
#
# Displays camera video stream.
# Using a Freenove ESP32 Wrover
#
substitutions:
  label: testcamera
  slug: test_camera
  name: Test Camera
  description: Displays camera video stream.
  encryption_key: !secret esphome_test_uptime_encryption_key
  ota_password: !secret esphome_test_uptime_ota_password

packages:
  device: !include devices/freenove_wrover.yaml

esp32_camera:
  external_clock:
    pin: GPIO21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  resolution: 640x480
  vertical_flip: False
  brightness: 0
  jpeg_quality: 10

  # Image settings
  name: ESP Camera
