---
# Test Display
#
# Displays device uptime on LCD.
# Using a Freenove ESP32 Wrover
#
substitutions:
  label: testdisplay
  slug: test_display
  name: Test Display
  description: Displays device uptime on LCD.
  encryption_key: !secret esphome_test_uptime_encryption_key
  ota_password: !secret esphome_test_uptime_ota_password

packages:
  device: !include devices/freenove_wrover.yaml
  i2c: !include components/i2c_esp32.yaml

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      switch (id(page)){
        case 1:
          {
            time_t raw_time = id(sensor_uptime_timestamp).state;
            struct tm * timeinfo;
            char buffer[20];
            timeinfo = localtime(&raw_time);
            strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M", timeinfo);
            it.printf("Uptime since");
            it.printf(0, 1, "%s", buffer);
            break;
          }
        case 2:
          it.printf("Wifi Signal");
          it.printf(0, 1, "%.0f%%", id(sensor_wifi_signal_percentage).state);
          break;
      }

globals:
- id: page
  type: int
  initial_value: "1"

interval:
- interval: 5s
  then:
    - lambda: |-
        id(page) = (id(page) + 1);
        if (id(page) > 2) {
          id(page) = 1;
        }
