substitutions:
  device_name: cc1101

external_components:
  - source: github://pr#6300
    components: [ cc1101 ]

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23
  interface: any

cc1101:
  id: transceiver
  cs_pin: GPIO5
  bandwidth: 200
  frequency: 433000
#  frequency: 868300
  rssi:
    name: "${device_name} rssi"
  lqi:
    name: "${device_name} lqi"

remote_transmitter:
  pin: GPIO2  # GDO0
  carrier_duty_percent: 100%

remote_receiver:
  pin: GPIO4  # GDO2
  dump:
    - rc_switch
    # - raw
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  buffer_size: 2kb
  filter: 250us
  idle: 4ms
  on_rc_switch:
    - logger.log:
        format: "on_rc_switch: %i %llu"
        args: [x.protocol, x.code]
